<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Pgvector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\core-libraries\Core.DDD\Core.DDD.csproj" />
    <ProjectReference Include="..\core-libraries\Core.Settings\Core.Settings.csproj" />
  </ItemGroup>

</Project>
