<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Auditing\Core.Auditing.csproj" />
    <ProjectReference Include="..\Core.DDD\Core.DDD.csproj" />
    <ProjectReference Include="..\Core.Notifications\Core.Notifications.csproj" />
    <ProjectReference Include="..\Core.OTP\Core.OTP.csproj" />
  </ItemGroup>

</Project>
