type Declaration = readonly [name: string, value: string];

const headerComment = '/* Generated by web/scripts/tokens/cli.ts from .claude/design-system.md. Do not edit. */';
const typographyPattern = /^(\d+)\/(\d+)(?:\s*·\s*(\d+)\/(\d+))?(?:,\s*tracking\s+(\S+))?/;
const spacingPattern = /^(\d+)(?:\s*mobile\s*·\s*(\d+)\s*desktop)?/;
const breakpointPattern = /^≥(\d+)$/;
const parenthetical = /\s*\([^)]*\)/g;

const tokenName = (token: string): string => `--ds-${token.replaceAll('.', '-')}`;
const firstInteger = (value: string): string => /\d+/.exec(value)?.[0] ?? '';
const beforeDash = (value: string): string => (value.split(' — ')[0] ?? '').trim();

function sectionRows(lines: readonly string[], prefix: string): string[][] {
  const start = lines.findIndex((line) => line.startsWith(prefix));
  if (start === -1) {
    throw new Error(`design-system: section "${prefix}" not found`);
  }
  const rest = lines.slice(start + 1);
  const end = rest.findIndex((line) => line.startsWith('#'));
  return (end === -1 ? rest : rest.slice(0, end))
    .filter((line) => line.startsWith('|'))
    .slice(1)
    .filter((line) => !/^\|\s*-/.test(line))
    .map((line) =>
      line
        .split('|')
        .slice(1, -1)
        .map((cell) => cell.trim()),
    );
}

function colour([, cssVar = '', value = '']: string[]): Declaration[] {
  return [[cssVar, value]];
}

function typography([token = '', , size = '', weight = '']: string[]): Declaration[] {
  const name = tokenName(token);
  const match = typographyPattern.exec(size.replace(parenthetical, ''));
  if (!match) {
    return [];
  }
  const [, mobileSize, mobileLine, desktopSize, desktopLine, tracking] = match;
  return [
    [`${name}-size`, `${mobileSize ?? ''}px`],
    [`${name}-line`, `${mobileLine ?? ''}px`],
    ...(desktopSize && desktopLine
      ? ([
          [`${name}-size-desktop`, `${desktopSize}px`],
          [`${name}-line-desktop`, `${desktopLine}px`],
        ] as const)
      : []),
    [`${name}-weight`, firstInteger(weight.replace(parenthetical, ''))],
    ...(tracking ? ([[`${name}-tracking`, tracking]] as const) : []),
  ];
}

function spacing([token = '', value = '']: string[]): Declaration[] {
  const name = tokenName(token);
  const match = spacingPattern.exec(value.replace(parenthetical, ''));
  if (!match) {
    return [];
  }
  const [, base, desktop] = match;
  return [[name, `${base ?? ''}px`], ...(desktop ? ([[`${name}-desktop`, `${desktop}px`]] as const) : [])];
}

function radius([token = '', value = '']: string[]): Declaration[] {
  const name = tokenName(token);
  if (token.startsWith('radius.')) {
    return [[name, `${firstInteger(value)}px`]];
  }
  if (token.startsWith('shadow.')) {
    return [[name, beforeDash(value)]];
  }
  if (token.startsWith('motion.')) {
    const motion = beforeDash(value);
    const space = motion.indexOf(' ');
    return [
      [`${name}-duration`, motion.slice(0, space)],
      [`${name}-easing`, motion.slice(space + 1)],
    ];
  }
  return [];
}

function breakpoint([token = '', value = '']: string[]): Declaration[] {
  const match = breakpointPattern.exec(value);
  return token.startsWith('bp.') && match ? [[`--breakpoint-${token.slice(3)}`, `${match[1] ?? ''}px`]] : [];
}

export function generateTokensCss(markdown: string): string {
  const lines = markdown.split(/\r?\n/);
  const rootDeclarations = [
    ...sectionRows(lines, '### Colour').flatMap(colour),
    ...sectionRows(lines, '### Typography').flatMap(typography),
    ...sectionRows(lines, '### Spacing').flatMap(spacing),
    ...sectionRows(lines, '### Radius').flatMap(radius),
  ];
  const breakpoints = sectionRows(lines, '## Breakpoints').flatMap(breakpoint);
  const declare = ([name, value]: Declaration): string => `  ${name}: ${value};`;

  return [
    headerComment,
    ':root {',
    ...rootDeclarations.map(declare),
    '}',
    '',
    '@theme {',
    '  --breakpoint-*: initial;',
    ...breakpoints.map(declare),
    '}',
    '',
  ].join('\n');
}
