using Core.Spreadsheets;
using Elmanhg.Application.Configuration.Shared;
using Elmanhg.Application.Exceptions;
using Elmanhg.Application.Shared.RichText;
using Elmanhg.Domain.Analytics;
using Elmanhg.Domain.Avatar;
using Elmanhg.Domain.ContentRetrieval;
using Elmanhg.Domain.EssayGrading;
using Elmanhg.Domain.MathStepGrading;
using Elmanhg.Domain.ExamBlueprints;
using Elmanhg.Domain.Identity;
using Elmanhg.Domain.Lessons;
using Elmanhg.Domain.Mastery;
using Elmanhg.Domain.Questions;
using Elmanhg.Domain.ReviewSessions;
using Elmanhg.Domain.RuntimeSettings;
using Elmanhg.Domain.Sessions;
using Elmanhg.Domain.SlaCalendars;
using Elmanhg.Domain.Subjects;
using Elmanhg.Domain.Subscriptions;
using Elmanhg.Domain.TeacherThreads;
using Elmanhg.Domain.Teachers;
using Elmanhg.Domain.TrainingData;
using Elmanhg.Domain.TrainingExports;
using Elmanhg.Domain.Units;
using Elmanhg.Infrastructure.AiService;
using Elmanhg.Infrastructure.Analytics;
using Elmanhg.Infrastructure.Avatar;
using Elmanhg.Infrastructure.ContentRetrieval;
using Elmanhg.Infrastructure.EssayGrading;
using Elmanhg.Infrastructure.MathStepGrading;
using Elmanhg.Infrastructure.ExamBlueprints;
using Elmanhg.Infrastructure.Hosting;
using Elmanhg.Infrastructure.Identity;
using Elmanhg.Infrastructure.Lessons;
using Elmanhg.Infrastructure.Mastery;
using Elmanhg.Infrastructure.Messaging;
using Elmanhg.Infrastructure.Invitations;
using Elmanhg.Infrastructure.OtpDelivery;
using Elmanhg.Infrastructure.Payments;
using Elmanhg.Infrastructure.Questions;
using Elmanhg.Infrastructure.ReviewSessions;
using Elmanhg.Infrastructure.RichText;
using Elmanhg.Infrastructure.RuntimeSettings;
using Elmanhg.Infrastructure.Sessions;
using Elmanhg.Infrastructure.SlaCalendars;
using Elmanhg.Infrastructure.Storage;
using Elmanhg.Infrastructure.Subjects;
using Elmanhg.Infrastructure.Subscriptions;
using Elmanhg.Infrastructure.TeacherThreads;
using Elmanhg.Infrastructure.Teachers;
using Elmanhg.Infrastructure.TrainingData;
using Elmanhg.Infrastructure.TrainingExports;
using Elmanhg.Infrastructure.Units;
using Microsoft.Extensions.DependencyInjection;

namespace Elmanhg.Infrastructure;

public static class DependencyInjection
{
    public static IServiceCollection AddInfrastructure(this IServiceCollection services)
    {
        services.AddOtpDelivery();
        services.AddInvitationEmail();
        services.AddMessaging();
        services.AddPayments();
        services.AddAiService();
        services.AddFileStorage();
        services.AddTrainingData();
        services.AddSingleton<IRichTextSanitizer, RichTextSanitizer>();
        services.AddSingleton<IRichTextExtractor, RichTextExtractor>();
        services.AddCoreSpreadsheets(options =>
        {
            options.UnreadableErrorCode = ErrorCodes.SpreadsheetUnreadable;
            options.RightToLeft = true;
        });
        services.AddScoped<IUserRepository, UserRepository>();
        services.AddScoped<IIssuedRefreshTokenRepository, IssuedRefreshTokenRepository>();
        services.AddScoped<ISubjectRepository, SubjectRepository>();
        services.AddScoped<ITeacherSubjectRepository, TeacherSubjectRepository>();
        services.AddScoped<ICurriculumUnitRepository, CurriculumUnitRepository>();
        services.AddScoped<ILessonRepository, LessonRepository>();
        services.AddScoped<ILessonOpeningRepository, LessonOpeningRepository>();
        services.AddScoped<IQuestionRepository, QuestionRepository>();
        services.AddScoped<IQuestionImportBatchRepository, QuestionImportBatchRepository>();
        services.AddScoped<IReviewSessionRepository, ReviewSessionRepository>();
        services.AddScoped<ISessionRepository, SessionRepository>();
        services.AddScoped<IQuestionMasteryRepository, QuestionMasteryRepository>();
        services.AddScoped<IExamBlueprintRepository, ExamBlueprintRepository>();
        services.AddScoped<ISubscriptionRepository, SubscriptionRepository>();
        services.AddScoped<IPaymentRepository, PaymentRepository>();
        services.AddScoped<ITeacherThreadRepository, TeacherThreadRepository>();
        services.AddScoped<ITeacherVoiceDraftRepository, TeacherVoiceDraftRepository>();
        services.AddScoped<ITeacherThreadSlaEventRepository, TeacherThreadSlaEventRepository>();
        services.AddScoped<ITeacherThreadOutOfAppReminderRepository, TeacherThreadOutOfAppReminderRepository>();
        services.AddScoped<IFunnelEventRepository, FunnelEventRepository>();
        services.AddScoped<IUserActivityDayRepository, UserActivityDayRepository>();
        services.AddScoped<ILessonContentChunkRepository, LessonContentChunkRepository>();
        services.AddScoped<ILessonContentIndexRepository, LessonContentIndexRepository>();
        services.AddScoped<IAvatarMessageUsageRepository, AvatarMessageUsageRepository>();
        services.AddScoped<IAvatarConversationRepository, AvatarConversationRepository>();
        services.AddScoped<IAttemptTrainingRecordRepository, AttemptTrainingRecordRepository>();
        services.AddScoped<IAvatarTrainingRecordRepository, AvatarTrainingRecordRepository>();
        services.AddScoped<ITeacherThreadTrainingRecordRepository, TeacherThreadTrainingRecordRepository>();
        services.AddScoped<IEssayGradeRepository, EssayGradeRepository>();
        services.AddScoped<IMathStepGradeRepository, MathStepGradeRepository>();
        services.AddScoped<IEssayGradeTrainingRecordRepository, EssayGradeTrainingRecordRepository>();
        services.AddScoped<ITrainingExportRepository, TrainingExportRepository>();
        services.AddScoped<IRuntimeSettingOverrideRepository, RuntimeSettingOverrideRepository>();
        services.AddScoped<IExamPeriodRepository, ExamPeriodRepository>();
        services.AddScoped<IInfrastructureConfigurationReader, InfrastructureConfigurationReader>();
        return services;
    }
}
