<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\core-libraries\Core.Auditing\Core.Auditing.csproj" />
    <ProjectReference Include="..\core-libraries\Core.Cache\Core.Cache.csproj" />
    <ProjectReference Include="..\core-libraries\Core.CQRS\Core.CQRS.csproj" />
    <ProjectReference Include="..\core-libraries\Core.Identity\Core.Identity.csproj" />
    <ProjectReference Include="..\core-libraries\Core.Localization\Core.Localization.csproj" />
    <ProjectReference Include="..\core-libraries\Core.Logging\Core.Logging.csproj" />
    <ProjectReference Include="..\core-libraries\Core.OTP\Core.OTP.csproj" />
    <ProjectReference Include="..\core-libraries\Core.Settings\Core.Settings.csproj" />
    <ProjectReference Include="..\core-libraries\Core.Spreadsheets\Core.Spreadsheets.csproj" />
    <ProjectReference Include="..\core-libraries\Core.Storage\Core.Storage.csproj" />
    <ProjectReference Include="..\core-libraries\Core.Utilities\Core.Utilities.csproj" />
    <ProjectReference Include="..\core-libraries\Core.Validation\Core.Validation.csproj" />
    <ProjectReference Include="..\Elmanhg.Domain\Elmanhg.Domain.csproj" />
  </ItemGroup>

</Project>
