/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as TeacherRouteRouteImport } from './routes/teacher/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminBlueprintsRouteImport } from './routes/admin/blueprints'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminExportRouteImport } from './routes/admin/export'
import { Route as AdminMoreRouteImport } from './routes/admin/more'
import { Route as AdminQuestionsRouteImport } from './routes/admin/questions'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as StudentAskRouteImport } from './routes/student/ask'
import { Route as StudentMoreRouteImport } from './routes/student/more'
import { Route as StudentMultiExamRouteImport } from './routes/student/multi-exam'
import { Route as StudentProgressRouteImport } from './routes/student/progress'
import { Route as StudentSubscriptionRouteImport } from './routes/student/subscription'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'
import { Route as TeacherInboxRouteImport } from './routes/teacher/inbox'
import { Route as TeacherStatsRouteImport } from './routes/teacher/stats'
import { Route as AdminLessonLessonIdRouteImport } from './routes/admin/lesson.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRouteRoute = TeacherRouteRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlueprintsRoute = AdminBlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMoreRoute = AdminMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentAskRoute = StudentAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentMoreRoute = StudentMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentMultiExamRoute = StudentMultiExamRouteImport.update({
  id: '/multi-exam',
  path: '/multi-exam',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentSubscriptionRoute = StudentSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => StudentRouteRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherInboxRoute = TeacherInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherStatsRoute = TeacherStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const AdminLessonLessonIdRoute = AdminLessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/teacher': typeof TeacherRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blueprints': typeof AdminBlueprintsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/ask': typeof StudentAskRoute
  '/student/more': typeof StudentMoreRoute
  '/student/multi-exam': typeof StudentMultiExamRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/subscription': typeof StudentSubscriptionRoute
  '/teacher/inbox': typeof TeacherInboxRoute
  '/teacher/stats': typeof TeacherStatsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/lesson/$lessonId': typeof AdminLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blueprints': typeof AdminBlueprintsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/ask': typeof StudentAskRoute
  '/student/more': typeof StudentMoreRoute
  '/student/multi-exam': typeof StudentMultiExamRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/subscription': typeof StudentSubscriptionRoute
  '/teacher/inbox': typeof TeacherInboxRoute
  '/teacher/stats': typeof TeacherStatsRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/admin/lesson/$lessonId': typeof AdminLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/teacher': typeof TeacherRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blueprints': typeof AdminBlueprintsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/ask': typeof StudentAskRoute
  '/student/more': typeof StudentMoreRoute
  '/student/multi-exam': typeof StudentMultiExamRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/subscription': typeof StudentSubscriptionRoute
  '/teacher/inbox': typeof TeacherInboxRoute
  '/teacher/stats': typeof TeacherStatsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/lesson/$lessonId': typeof AdminLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/login'
    | '/signup'
    | '/admin/audit'
    | '/admin/blueprints'
    | '/admin/content'
    | '/admin/export'
    | '/admin/more'
    | '/admin/questions'
    | '/admin/users'
    | '/student/ask'
    | '/student/more'
    | '/student/multi-exam'
    | '/student/progress'
    | '/student/subscription'
    | '/teacher/inbox'
    | '/teacher/stats'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/admin/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/audit'
    | '/admin/blueprints'
    | '/admin/content'
    | '/admin/export'
    | '/admin/more'
    | '/admin/questions'
    | '/admin/users'
    | '/student/ask'
    | '/student/more'
    | '/student/multi-exam'
    | '/student/progress'
    | '/student/subscription'
    | '/teacher/inbox'
    | '/teacher/stats'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/admin/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/login'
    | '/signup'
    | '/admin/audit'
    | '/admin/blueprints'
    | '/admin/content'
    | '/admin/export'
    | '/admin/more'
    | '/admin/questions'
    | '/admin/users'
    | '/student/ask'
    | '/student/more'
    | '/student/multi-exam'
    | '/student/progress'
    | '/student/subscription'
    | '/teacher/inbox'
    | '/teacher/stats'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/admin/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  TeacherRouteRoute: typeof TeacherRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blueprints': {
      id: '/admin/blueprints'
      path: '/blueprints'
      fullPath: '/admin/blueprints'
      preLoaderRoute: typeof AdminBlueprintsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/more': {
      id: '/admin/more'
      path: '/more'
      fullPath: '/admin/more'
      preLoaderRoute: typeof AdminMoreRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/ask': {
      id: '/student/ask'
      path: '/ask'
      fullPath: '/student/ask'
      preLoaderRoute: typeof StudentAskRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/more': {
      id: '/student/more'
      path: '/more'
      fullPath: '/student/more'
      preLoaderRoute: typeof StudentMoreRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/multi-exam': {
      id: '/student/multi-exam'
      path: '/multi-exam'
      fullPath: '/student/multi-exam'
      preLoaderRoute: typeof StudentMultiExamRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/subscription': {
      id: '/student/subscription'
      path: '/subscription'
      fullPath: '/student/subscription'
      preLoaderRoute: typeof StudentSubscriptionRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/inbox': {
      id: '/teacher/inbox'
      path: '/inbox'
      fullPath: '/teacher/inbox'
      preLoaderRoute: typeof TeacherInboxRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/stats': {
      id: '/teacher/stats'
      path: '/stats'
      fullPath: '/teacher/stats'
      preLoaderRoute: typeof TeacherStatsRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/admin/lesson/$lessonId': {
      id: '/admin/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/admin/lesson/$lessonId'
      preLoaderRoute: typeof AdminLessonLessonIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBlueprintsRoute: typeof AdminBlueprintsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminMoreRoute: typeof AdminMoreRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLessonLessonIdRoute: typeof AdminLessonLessonIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBlueprintsRoute: AdminBlueprintsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminExportRoute: AdminExportRoute,
  AdminMoreRoute: AdminMoreRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminLessonLessonIdRoute: AdminLessonLessonIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StudentRouteRouteChildren {
  StudentAskRoute: typeof StudentAskRoute
  StudentMoreRoute: typeof StudentMoreRoute
  StudentMultiExamRoute: typeof StudentMultiExamRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentSubscriptionRoute: typeof StudentSubscriptionRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentAskRoute: StudentAskRoute,
  StudentMoreRoute: StudentMoreRoute,
  StudentMultiExamRoute: StudentMultiExamRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentSubscriptionRoute: StudentSubscriptionRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

interface TeacherRouteRouteChildren {
  TeacherInboxRoute: typeof TeacherInboxRoute
  TeacherStatsRoute: typeof TeacherStatsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteRouteChildren: TeacherRouteRouteChildren = {
  TeacherInboxRoute: TeacherInboxRoute,
  TeacherStatsRoute: TeacherStatsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteRouteWithChildren = TeacherRouteRoute._addFileChildren(
  TeacherRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  TeacherRouteRoute: TeacherRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
