/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as TeacherRouteRouteImport } from './routes/teacher/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminBlueprintsRouteImport } from './routes/admin/blueprints'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminExportRouteImport } from './routes/admin/export'
import { Route as AdminMoreRouteImport } from './routes/admin/more'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminQuestionsRouteImport } from './routes/admin/questions'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as StudentAskRouteImport } from './routes/student/ask'
import { Route as StudentMoreRouteImport } from './routes/student/more'
import { Route as StudentMultiExamRouteImport } from './routes/student/multi-exam'
import { Route as StudentProgressRouteImport } from './routes/student/progress'
import { Route as StudentSubscriptionRouteImport } from './routes/student/subscription'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'
import { Route as TeacherInboxRouteImport } from './routes/teacher/inbox'
import { Route as TeacherStatsRouteImport } from './routes/teacher/stats'
import { Route as AdminLessonLessonIdRouteImport } from './routes/admin/lesson.$lessonId'
import { Route as AdminQuestionQuestionIdRouteImport } from './routes/admin/question.$questionId'
import { Route as StudentCheckoutResultPaymentIdRouteImport } from './routes/student/checkout-result.$paymentId'
import { Route as StudentExamResultSessionIdRouteImport } from './routes/student/exam-result.$sessionId'
import { Route as StudentExamStartUnitIdRouteImport } from './routes/student/exam-start.$unitId'
import { Route as StudentExamSessionIdRouteImport } from './routes/student/exam.$sessionId'
import { Route as StudentFakeCheckoutPaymentIdRouteImport } from './routes/student/fake-checkout.$paymentId'
import { Route as StudentLessonLessonIdRouteImport } from './routes/student/lesson.$lessonId'
import { Route as StudentQuizResultSessionIdRouteImport } from './routes/student/quiz-result.$sessionId'
import { Route as StudentQuizSessionIdRouteImport } from './routes/student/quiz.$sessionId'
import { Route as StudentSubjectSubjectIdRouteImport } from './routes/student/subject.$subjectId'
import { Route as StudentUnitUnitIdRouteImport } from './routes/student/unit.$unitId'
import { Route as TeacherQQuestionIdRouteImport } from './routes/teacher/q.$questionId'
import { Route as AdminQuestionImportLessonIdRouteImport } from './routes/admin/question.import.$lessonId'
import { Route as AdminQuestionNewLessonIdRouteImport } from './routes/admin/question.new.$lessonId'
import { Route as StudentLessonLessonIdIndexRouteImport } from './routes/student/lesson.$lessonId.index'
import { Route as StudentLessonLessonIdObjectivesRouteImport } from './routes/student/lesson.$lessonId.objectives'
import { Route as StudentLessonLessonIdPracticeRouteImport } from './routes/student/lesson.$lessonId.practice'
import { Route as StudentLessonLessonIdSummaryRouteImport } from './routes/student/lesson.$lessonId.summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRouteRoute = TeacherRouteRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlueprintsRoute = AdminBlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMoreRoute = AdminMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentAskRoute = StudentAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentMoreRoute = StudentMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentMultiExamRoute = StudentMultiExamRouteImport.update({
  id: '/multi-exam',
  path: '/multi-exam',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentSubscriptionRoute = StudentSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => StudentRouteRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherInboxRoute = TeacherInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherStatsRoute = TeacherStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const AdminLessonLessonIdRoute = AdminLessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminQuestionQuestionIdRoute = AdminQuestionQuestionIdRouteImport.update({
  id: '/question/$questionId',
  path: '/question/$questionId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StudentCheckoutResultPaymentIdRoute =
  StudentCheckoutResultPaymentIdRouteImport.update({
    id: '/checkout-result/$paymentId',
    path: '/checkout-result/$paymentId',
    getParentRoute: () => StudentRouteRoute,
  } as any)
const StudentExamResultSessionIdRoute =
  StudentExamResultSessionIdRouteImport.update({
    id: '/exam-result/$sessionId',
    path: '/exam-result/$sessionId',
    getParentRoute: () => StudentRouteRoute,
  } as any)
const StudentExamStartUnitIdRoute = StudentExamStartUnitIdRouteImport.update({
  id: '/exam-start/$unitId',
  path: '/exam-start/$unitId',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentExamSessionIdRoute = StudentExamSessionIdRouteImport.update({
  id: '/exam/$sessionId',
  path: '/exam/$sessionId',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentFakeCheckoutPaymentIdRoute =
  StudentFakeCheckoutPaymentIdRouteImport.update({
    id: '/fake-checkout/$paymentId',
    path: '/fake-checkout/$paymentId',
    getParentRoute: () => StudentRouteRoute,
  } as any)
const StudentLessonLessonIdRoute = StudentLessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentQuizResultSessionIdRoute =
  StudentQuizResultSessionIdRouteImport.update({
    id: '/quiz-result/$sessionId',
    path: '/quiz-result/$sessionId',
    getParentRoute: () => StudentRouteRoute,
  } as any)
const StudentQuizSessionIdRoute = StudentQuizSessionIdRouteImport.update({
  id: '/quiz/$sessionId',
  path: '/quiz/$sessionId',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentSubjectSubjectIdRoute = StudentSubjectSubjectIdRouteImport.update({
  id: '/subject/$subjectId',
  path: '/subject/$subjectId',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentUnitUnitIdRoute = StudentUnitUnitIdRouteImport.update({
  id: '/unit/$unitId',
  path: '/unit/$unitId',
  getParentRoute: () => StudentRouteRoute,
} as any)
const TeacherQQuestionIdRoute = TeacherQQuestionIdRouteImport.update({
  id: '/q/$questionId',
  path: '/q/$questionId',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const AdminQuestionImportLessonIdRoute =
  AdminQuestionImportLessonIdRouteImport.update({
    id: '/question/import/$lessonId',
    path: '/question/import/$lessonId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminQuestionNewLessonIdRoute =
  AdminQuestionNewLessonIdRouteImport.update({
    id: '/question/new/$lessonId',
    path: '/question/new/$lessonId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const StudentLessonLessonIdIndexRoute =
  StudentLessonLessonIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudentLessonLessonIdRoute,
  } as any)
const StudentLessonLessonIdObjectivesRoute =
  StudentLessonLessonIdObjectivesRouteImport.update({
    id: '/objectives',
    path: '/objectives',
    getParentRoute: () => StudentLessonLessonIdRoute,
  } as any)
const StudentLessonLessonIdPracticeRoute =
  StudentLessonLessonIdPracticeRouteImport.update({
    id: '/practice',
    path: '/practice',
    getParentRoute: () => StudentLessonLessonIdRoute,
  } as any)
const StudentLessonLessonIdSummaryRoute =
  StudentLessonLessonIdSummaryRouteImport.update({
    id: '/summary',
    path: '/summary',
    getParentRoute: () => StudentLessonLessonIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/teacher': typeof TeacherRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blueprints': typeof AdminBlueprintsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/ask': typeof StudentAskRoute
  '/student/more': typeof StudentMoreRoute
  '/student/multi-exam': typeof StudentMultiExamRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/subscription': typeof StudentSubscriptionRoute
  '/teacher/inbox': typeof TeacherInboxRoute
  '/teacher/stats': typeof TeacherStatsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/lesson/$lessonId': typeof AdminLessonLessonIdRoute
  '/admin/question/$questionId': typeof AdminQuestionQuestionIdRoute
  '/student/checkout-result/$paymentId': typeof StudentCheckoutResultPaymentIdRoute
  '/student/exam-result/$sessionId': typeof StudentExamResultSessionIdRoute
  '/student/exam-start/$unitId': typeof StudentExamStartUnitIdRoute
  '/student/exam/$sessionId': typeof StudentExamSessionIdRoute
  '/student/fake-checkout/$paymentId': typeof StudentFakeCheckoutPaymentIdRoute
  '/student/lesson/$lessonId': typeof StudentLessonLessonIdRouteWithChildren
  '/student/quiz-result/$sessionId': typeof StudentQuizResultSessionIdRoute
  '/student/quiz/$sessionId': typeof StudentQuizSessionIdRoute
  '/student/subject/$subjectId': typeof StudentSubjectSubjectIdRoute
  '/student/unit/$unitId': typeof StudentUnitUnitIdRoute
  '/teacher/q/$questionId': typeof TeacherQQuestionIdRoute
  '/admin/question/import/$lessonId': typeof AdminQuestionImportLessonIdRoute
  '/admin/question/new/$lessonId': typeof AdminQuestionNewLessonIdRoute
  '/student/lesson/$lessonId/objectives': typeof StudentLessonLessonIdObjectivesRoute
  '/student/lesson/$lessonId/practice': typeof StudentLessonLessonIdPracticeRoute
  '/student/lesson/$lessonId/summary': typeof StudentLessonLessonIdSummaryRoute
  '/student/lesson/$lessonId/': typeof StudentLessonLessonIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blueprints': typeof AdminBlueprintsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/ask': typeof StudentAskRoute
  '/student/more': typeof StudentMoreRoute
  '/student/multi-exam': typeof StudentMultiExamRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/subscription': typeof StudentSubscriptionRoute
  '/teacher/inbox': typeof TeacherInboxRoute
  '/teacher/stats': typeof TeacherStatsRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/admin/lesson/$lessonId': typeof AdminLessonLessonIdRoute
  '/admin/question/$questionId': typeof AdminQuestionQuestionIdRoute
  '/student/checkout-result/$paymentId': typeof StudentCheckoutResultPaymentIdRoute
  '/student/exam-result/$sessionId': typeof StudentExamResultSessionIdRoute
  '/student/exam-start/$unitId': typeof StudentExamStartUnitIdRoute
  '/student/exam/$sessionId': typeof StudentExamSessionIdRoute
  '/student/fake-checkout/$paymentId': typeof StudentFakeCheckoutPaymentIdRoute
  '/student/quiz-result/$sessionId': typeof StudentQuizResultSessionIdRoute
  '/student/quiz/$sessionId': typeof StudentQuizSessionIdRoute
  '/student/subject/$subjectId': typeof StudentSubjectSubjectIdRoute
  '/student/unit/$unitId': typeof StudentUnitUnitIdRoute
  '/teacher/q/$questionId': typeof TeacherQQuestionIdRoute
  '/admin/question/import/$lessonId': typeof AdminQuestionImportLessonIdRoute
  '/admin/question/new/$lessonId': typeof AdminQuestionNewLessonIdRoute
  '/student/lesson/$lessonId/objectives': typeof StudentLessonLessonIdObjectivesRoute
  '/student/lesson/$lessonId/practice': typeof StudentLessonLessonIdPracticeRoute
  '/student/lesson/$lessonId/summary': typeof StudentLessonLessonIdSummaryRoute
  '/student/lesson/$lessonId': typeof StudentLessonLessonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/teacher': typeof TeacherRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blueprints': typeof AdminBlueprintsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/ask': typeof StudentAskRoute
  '/student/more': typeof StudentMoreRoute
  '/student/multi-exam': typeof StudentMultiExamRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/subscription': typeof StudentSubscriptionRoute
  '/teacher/inbox': typeof TeacherInboxRoute
  '/teacher/stats': typeof TeacherStatsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/lesson/$lessonId': typeof AdminLessonLessonIdRoute
  '/admin/question/$questionId': typeof AdminQuestionQuestionIdRoute
  '/student/checkout-result/$paymentId': typeof StudentCheckoutResultPaymentIdRoute
  '/student/exam-result/$sessionId': typeof StudentExamResultSessionIdRoute
  '/student/exam-start/$unitId': typeof StudentExamStartUnitIdRoute
  '/student/exam/$sessionId': typeof StudentExamSessionIdRoute
  '/student/fake-checkout/$paymentId': typeof StudentFakeCheckoutPaymentIdRoute
  '/student/lesson/$lessonId': typeof StudentLessonLessonIdRouteWithChildren
  '/student/quiz-result/$sessionId': typeof StudentQuizResultSessionIdRoute
  '/student/quiz/$sessionId': typeof StudentQuizSessionIdRoute
  '/student/subject/$subjectId': typeof StudentSubjectSubjectIdRoute
  '/student/unit/$unitId': typeof StudentUnitUnitIdRoute
  '/teacher/q/$questionId': typeof TeacherQQuestionIdRoute
  '/admin/question/import/$lessonId': typeof AdminQuestionImportLessonIdRoute
  '/admin/question/new/$lessonId': typeof AdminQuestionNewLessonIdRoute
  '/student/lesson/$lessonId/objectives': typeof StudentLessonLessonIdObjectivesRoute
  '/student/lesson/$lessonId/practice': typeof StudentLessonLessonIdPracticeRoute
  '/student/lesson/$lessonId/summary': typeof StudentLessonLessonIdSummaryRoute
  '/student/lesson/$lessonId/': typeof StudentLessonLessonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/login'
    | '/signup'
    | '/admin/audit'
    | '/admin/blueprints'
    | '/admin/content'
    | '/admin/export'
    | '/admin/more'
    | '/admin/payments'
    | '/admin/questions'
    | '/admin/users'
    | '/student/ask'
    | '/student/more'
    | '/student/multi-exam'
    | '/student/progress'
    | '/student/subscription'
    | '/teacher/inbox'
    | '/teacher/stats'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/admin/lesson/$lessonId'
    | '/admin/question/$questionId'
    | '/student/checkout-result/$paymentId'
    | '/student/exam-result/$sessionId'
    | '/student/exam-start/$unitId'
    | '/student/exam/$sessionId'
    | '/student/fake-checkout/$paymentId'
    | '/student/lesson/$lessonId'
    | '/student/quiz-result/$sessionId'
    | '/student/quiz/$sessionId'
    | '/student/subject/$subjectId'
    | '/student/unit/$unitId'
    | '/teacher/q/$questionId'
    | '/admin/question/import/$lessonId'
    | '/admin/question/new/$lessonId'
    | '/student/lesson/$lessonId/objectives'
    | '/student/lesson/$lessonId/practice'
    | '/student/lesson/$lessonId/summary'
    | '/student/lesson/$lessonId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/audit'
    | '/admin/blueprints'
    | '/admin/content'
    | '/admin/export'
    | '/admin/more'
    | '/admin/payments'
    | '/admin/questions'
    | '/admin/users'
    | '/student/ask'
    | '/student/more'
    | '/student/multi-exam'
    | '/student/progress'
    | '/student/subscription'
    | '/teacher/inbox'
    | '/teacher/stats'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/admin/lesson/$lessonId'
    | '/admin/question/$questionId'
    | '/student/checkout-result/$paymentId'
    | '/student/exam-result/$sessionId'
    | '/student/exam-start/$unitId'
    | '/student/exam/$sessionId'
    | '/student/fake-checkout/$paymentId'
    | '/student/quiz-result/$sessionId'
    | '/student/quiz/$sessionId'
    | '/student/subject/$subjectId'
    | '/student/unit/$unitId'
    | '/teacher/q/$questionId'
    | '/admin/question/import/$lessonId'
    | '/admin/question/new/$lessonId'
    | '/student/lesson/$lessonId/objectives'
    | '/student/lesson/$lessonId/practice'
    | '/student/lesson/$lessonId/summary'
    | '/student/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/login'
    | '/signup'
    | '/admin/audit'
    | '/admin/blueprints'
    | '/admin/content'
    | '/admin/export'
    | '/admin/more'
    | '/admin/payments'
    | '/admin/questions'
    | '/admin/users'
    | '/student/ask'
    | '/student/more'
    | '/student/multi-exam'
    | '/student/progress'
    | '/student/subscription'
    | '/teacher/inbox'
    | '/teacher/stats'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/admin/lesson/$lessonId'
    | '/admin/question/$questionId'
    | '/student/checkout-result/$paymentId'
    | '/student/exam-result/$sessionId'
    | '/student/exam-start/$unitId'
    | '/student/exam/$sessionId'
    | '/student/fake-checkout/$paymentId'
    | '/student/lesson/$lessonId'
    | '/student/quiz-result/$sessionId'
    | '/student/quiz/$sessionId'
    | '/student/subject/$subjectId'
    | '/student/unit/$unitId'
    | '/teacher/q/$questionId'
    | '/admin/question/import/$lessonId'
    | '/admin/question/new/$lessonId'
    | '/student/lesson/$lessonId/objectives'
    | '/student/lesson/$lessonId/practice'
    | '/student/lesson/$lessonId/summary'
    | '/student/lesson/$lessonId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  TeacherRouteRoute: typeof TeacherRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blueprints': {
      id: '/admin/blueprints'
      path: '/blueprints'
      fullPath: '/admin/blueprints'
      preLoaderRoute: typeof AdminBlueprintsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/more': {
      id: '/admin/more'
      path: '/more'
      fullPath: '/admin/more'
      preLoaderRoute: typeof AdminMoreRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/ask': {
      id: '/student/ask'
      path: '/ask'
      fullPath: '/student/ask'
      preLoaderRoute: typeof StudentAskRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/more': {
      id: '/student/more'
      path: '/more'
      fullPath: '/student/more'
      preLoaderRoute: typeof StudentMoreRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/multi-exam': {
      id: '/student/multi-exam'
      path: '/multi-exam'
      fullPath: '/student/multi-exam'
      preLoaderRoute: typeof StudentMultiExamRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/subscription': {
      id: '/student/subscription'
      path: '/subscription'
      fullPath: '/student/subscription'
      preLoaderRoute: typeof StudentSubscriptionRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/inbox': {
      id: '/teacher/inbox'
      path: '/inbox'
      fullPath: '/teacher/inbox'
      preLoaderRoute: typeof TeacherInboxRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/stats': {
      id: '/teacher/stats'
      path: '/stats'
      fullPath: '/teacher/stats'
      preLoaderRoute: typeof TeacherStatsRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/admin/lesson/$lessonId': {
      id: '/admin/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/admin/lesson/$lessonId'
      preLoaderRoute: typeof AdminLessonLessonIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/question/$questionId': {
      id: '/admin/question/$questionId'
      path: '/question/$questionId'
      fullPath: '/admin/question/$questionId'
      preLoaderRoute: typeof AdminQuestionQuestionIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/student/checkout-result/$paymentId': {
      id: '/student/checkout-result/$paymentId'
      path: '/checkout-result/$paymentId'
      fullPath: '/student/checkout-result/$paymentId'
      preLoaderRoute: typeof StudentCheckoutResultPaymentIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/exam-result/$sessionId': {
      id: '/student/exam-result/$sessionId'
      path: '/exam-result/$sessionId'
      fullPath: '/student/exam-result/$sessionId'
      preLoaderRoute: typeof StudentExamResultSessionIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/exam-start/$unitId': {
      id: '/student/exam-start/$unitId'
      path: '/exam-start/$unitId'
      fullPath: '/student/exam-start/$unitId'
      preLoaderRoute: typeof StudentExamStartUnitIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/exam/$sessionId': {
      id: '/student/exam/$sessionId'
      path: '/exam/$sessionId'
      fullPath: '/student/exam/$sessionId'
      preLoaderRoute: typeof StudentExamSessionIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/fake-checkout/$paymentId': {
      id: '/student/fake-checkout/$paymentId'
      path: '/fake-checkout/$paymentId'
      fullPath: '/student/fake-checkout/$paymentId'
      preLoaderRoute: typeof StudentFakeCheckoutPaymentIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/lesson/$lessonId': {
      id: '/student/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/student/lesson/$lessonId'
      preLoaderRoute: typeof StudentLessonLessonIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/quiz-result/$sessionId': {
      id: '/student/quiz-result/$sessionId'
      path: '/quiz-result/$sessionId'
      fullPath: '/student/quiz-result/$sessionId'
      preLoaderRoute: typeof StudentQuizResultSessionIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/quiz/$sessionId': {
      id: '/student/quiz/$sessionId'
      path: '/quiz/$sessionId'
      fullPath: '/student/quiz/$sessionId'
      preLoaderRoute: typeof StudentQuizSessionIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/subject/$subjectId': {
      id: '/student/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/student/subject/$subjectId'
      preLoaderRoute: typeof StudentSubjectSubjectIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/unit/$unitId': {
      id: '/student/unit/$unitId'
      path: '/unit/$unitId'
      fullPath: '/student/unit/$unitId'
      preLoaderRoute: typeof StudentUnitUnitIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/teacher/q/$questionId': {
      id: '/teacher/q/$questionId'
      path: '/q/$questionId'
      fullPath: '/teacher/q/$questionId'
      preLoaderRoute: typeof TeacherQQuestionIdRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/admin/question/import/$lessonId': {
      id: '/admin/question/import/$lessonId'
      path: '/question/import/$lessonId'
      fullPath: '/admin/question/import/$lessonId'
      preLoaderRoute: typeof AdminQuestionImportLessonIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/question/new/$lessonId': {
      id: '/admin/question/new/$lessonId'
      path: '/question/new/$lessonId'
      fullPath: '/admin/question/new/$lessonId'
      preLoaderRoute: typeof AdminQuestionNewLessonIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/student/lesson/$lessonId/': {
      id: '/student/lesson/$lessonId/'
      path: '/'
      fullPath: '/student/lesson/$lessonId/'
      preLoaderRoute: typeof StudentLessonLessonIdIndexRouteImport
      parentRoute: typeof StudentLessonLessonIdRoute
    }
    '/student/lesson/$lessonId/objectives': {
      id: '/student/lesson/$lessonId/objectives'
      path: '/objectives'
      fullPath: '/student/lesson/$lessonId/objectives'
      preLoaderRoute: typeof StudentLessonLessonIdObjectivesRouteImport
      parentRoute: typeof StudentLessonLessonIdRoute
    }
    '/student/lesson/$lessonId/practice': {
      id: '/student/lesson/$lessonId/practice'
      path: '/practice'
      fullPath: '/student/lesson/$lessonId/practice'
      preLoaderRoute: typeof StudentLessonLessonIdPracticeRouteImport
      parentRoute: typeof StudentLessonLessonIdRoute
    }
    '/student/lesson/$lessonId/summary': {
      id: '/student/lesson/$lessonId/summary'
      path: '/summary'
      fullPath: '/student/lesson/$lessonId/summary'
      preLoaderRoute: typeof StudentLessonLessonIdSummaryRouteImport
      parentRoute: typeof StudentLessonLessonIdRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBlueprintsRoute: typeof AdminBlueprintsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminMoreRoute: typeof AdminMoreRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLessonLessonIdRoute: typeof AdminLessonLessonIdRoute
  AdminQuestionQuestionIdRoute: typeof AdminQuestionQuestionIdRoute
  AdminQuestionImportLessonIdRoute: typeof AdminQuestionImportLessonIdRoute
  AdminQuestionNewLessonIdRoute: typeof AdminQuestionNewLessonIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBlueprintsRoute: AdminBlueprintsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminExportRoute: AdminExportRoute,
  AdminMoreRoute: AdminMoreRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminLessonLessonIdRoute: AdminLessonLessonIdRoute,
  AdminQuestionQuestionIdRoute: AdminQuestionQuestionIdRoute,
  AdminQuestionImportLessonIdRoute: AdminQuestionImportLessonIdRoute,
  AdminQuestionNewLessonIdRoute: AdminQuestionNewLessonIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StudentLessonLessonIdRouteChildren {
  StudentLessonLessonIdObjectivesRoute: typeof StudentLessonLessonIdObjectivesRoute
  StudentLessonLessonIdPracticeRoute: typeof StudentLessonLessonIdPracticeRoute
  StudentLessonLessonIdSummaryRoute: typeof StudentLessonLessonIdSummaryRoute
  StudentLessonLessonIdIndexRoute: typeof StudentLessonLessonIdIndexRoute
}

const StudentLessonLessonIdRouteChildren: StudentLessonLessonIdRouteChildren = {
  StudentLessonLessonIdObjectivesRoute: StudentLessonLessonIdObjectivesRoute,
  StudentLessonLessonIdPracticeRoute: StudentLessonLessonIdPracticeRoute,
  StudentLessonLessonIdSummaryRoute: StudentLessonLessonIdSummaryRoute,
  StudentLessonLessonIdIndexRoute: StudentLessonLessonIdIndexRoute,
}

const StudentLessonLessonIdRouteWithChildren =
  StudentLessonLessonIdRoute._addFileChildren(
    StudentLessonLessonIdRouteChildren,
  )

interface StudentRouteRouteChildren {
  StudentAskRoute: typeof StudentAskRoute
  StudentMoreRoute: typeof StudentMoreRoute
  StudentMultiExamRoute: typeof StudentMultiExamRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentSubscriptionRoute: typeof StudentSubscriptionRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentCheckoutResultPaymentIdRoute: typeof StudentCheckoutResultPaymentIdRoute
  StudentExamResultSessionIdRoute: typeof StudentExamResultSessionIdRoute
  StudentExamStartUnitIdRoute: typeof StudentExamStartUnitIdRoute
  StudentExamSessionIdRoute: typeof StudentExamSessionIdRoute
  StudentFakeCheckoutPaymentIdRoute: typeof StudentFakeCheckoutPaymentIdRoute
  StudentLessonLessonIdRoute: typeof StudentLessonLessonIdRouteWithChildren
  StudentQuizResultSessionIdRoute: typeof StudentQuizResultSessionIdRoute
  StudentQuizSessionIdRoute: typeof StudentQuizSessionIdRoute
  StudentSubjectSubjectIdRoute: typeof StudentSubjectSubjectIdRoute
  StudentUnitUnitIdRoute: typeof StudentUnitUnitIdRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentAskRoute: StudentAskRoute,
  StudentMoreRoute: StudentMoreRoute,
  StudentMultiExamRoute: StudentMultiExamRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentSubscriptionRoute: StudentSubscriptionRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentCheckoutResultPaymentIdRoute: StudentCheckoutResultPaymentIdRoute,
  StudentExamResultSessionIdRoute: StudentExamResultSessionIdRoute,
  StudentExamStartUnitIdRoute: StudentExamStartUnitIdRoute,
  StudentExamSessionIdRoute: StudentExamSessionIdRoute,
  StudentFakeCheckoutPaymentIdRoute: StudentFakeCheckoutPaymentIdRoute,
  StudentLessonLessonIdRoute: StudentLessonLessonIdRouteWithChildren,
  StudentQuizResultSessionIdRoute: StudentQuizResultSessionIdRoute,
  StudentQuizSessionIdRoute: StudentQuizSessionIdRoute,
  StudentSubjectSubjectIdRoute: StudentSubjectSubjectIdRoute,
  StudentUnitUnitIdRoute: StudentUnitUnitIdRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

interface TeacherRouteRouteChildren {
  TeacherInboxRoute: typeof TeacherInboxRoute
  TeacherStatsRoute: typeof TeacherStatsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherQQuestionIdRoute: typeof TeacherQQuestionIdRoute
}

const TeacherRouteRouteChildren: TeacherRouteRouteChildren = {
  TeacherInboxRoute: TeacherInboxRoute,
  TeacherStatsRoute: TeacherStatsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherQQuestionIdRoute: TeacherQQuestionIdRoute,
}

const TeacherRouteRouteWithChildren = TeacherRouteRoute._addFileChildren(
  TeacherRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  TeacherRouteRoute: TeacherRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
